services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_service
    env_file:
      - .env
    ports:
      - "8082:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0-oracle
    container_name: mysql_db
    env_file:
      - .env
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/schema.sql:ro

volumes:
  my-db:
